In [214]:
import pandas as pd
import sklearn.model_selection

Kindly refer to the link mentioned after #

In [215]:
df = pd.read_csv("REV_dataset.csv")
df

No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [216]:
df.set_index('No', inplace=True)

In [217]:
df

X1 transaction date  X2 house age  \
No                                       
1               2012.917          32.0   
2               2012.917          19.5   
3               2013.583          13.3   
4               2013.500          13.3   
5               2012.833           5.0   
..                   ...           ...   
410             2013.000          13.7   
411             2012.667           5.6   
412             2013.250          18.8   
413             2013.000           8.1   
414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
No                                                                             
1                                  84.87882                               10   
2                                 306.59470                                9   
3                                 561.98450                                5   
4                                 561.98450                                5   
5                                 390.56840                                5   
..                                      ...                              ...   
410                              4082.01500                                0   
411                                90.45606                                9   
412                               390.96960                                7   
413                               104.81010                                5   
414                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
No                                                          
1       24.98298     121.54024                        37.9  
2       24.98034     121.53951                        42.2  
3       24.98746     121.54391                        47.3  
4       24.98746     121.54391                        54.8  
5       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
410     24.94155     121.50381                        15.4  
411     24.97433     121.54310                        50.0  
412     24.97923     121.53986                        40.6  
413     24.96674     121.54067                        52.5  
414     24.97433     121.54310                        63.9  

[414 rows x 7 columns]

In [218]:
df = df.rename(columns = {"X1 transaction date" : "transation dt",
                      " X2 house age ": "house age ",
                      "X3 distance to the nearest MRT station" : "Nearest mtro",
                    "X4 number of convenience stores" : "nrby stores ",
                    "X5 latitude" : "latitude",
                     "X6 longitude": "longitude",
                    "Y house price of unit area" : "house price"})

In [219]:
# Making X variable
x = df.drop(['house price'] , axis = 1)
x

transation dt  X2 house age  Nearest mtro  nrby stores   latitude  \
No                                                                       
1         2012.917          32.0      84.87882            10  24.98298   
2         2012.917          19.5     306.59470             9  24.98034   
3         2013.583          13.3     561.98450             5  24.98746   
4         2013.500          13.3     561.98450             5  24.98746   
5         2012.833           5.0     390.56840             5  24.97937   
..             ...           ...           ...           ...       ...   
410       2013.000          13.7    4082.01500             0  24.94155   
411       2012.667           5.6      90.45606             9  24.97433   
412       2013.250          18.8     390.96960             7  24.97923   
413       2013.000           8.1     104.81010             5  24.96674   
414       2013.500           6.5      90.45606             9  24.97433   

     longitude  
No              
1    121.54024  
2    121.53951  
3    121.54391  
4    121.54391  
5    121.54245  
..         ...  
410  121.50381  
411  121.54310  
412  121.53986  
413  121.54067  
414  121.54310  

[414 rows x 6 columns]

In [220]:
# Making Y variable
y = df['house price']
y

No
1      37.9
2      42.2
3      47.3
4      54.8
5      43.1
       ... 
410    15.4
411    50.0
412    40.6
413    52.5
414    63.9
Name: house price, Length: 414, dtype: float64

In [221]:
print("X_shape : ",x.shape)
print("Y_shape : ",y.shape)

X_shape :  (414, 6)
Y_shape :  (414,)


In [222]:
# ('https://www.greycampus.com/blog/data-science/linear-regression-with-python-scikit-learn')
from sklearn.model_selection import train_test_split 
X_train , X_test , y_train , y_test = train_test_split(x,y , test_size = 0.2 , random_state = 14)

In [223]:
print('X_train_shape : ' , X_train.shape )
print('y_train_shape : ' , y_train.shape )
print('X_test_shape : ' , X_test.shape )
print('y_test_shape : ' , y_test.shape )

X_train_shape :  (331, 6)
y_train_shape :  (331,)
X_test_shape :  (83, 6)
y_test_shape :  (83,)


In [224]:
from sklearn.preprocessing import StandardScaler 
sclr = StandardScaler()
sclr.fit(X_train)
X_train = sclr.transform(X_train)
X_test = sclr.transform(X_test)

In [225]:
from sklearn.linear_model import LinearRegression
l_model = LinearRegression()
l_model.fit(X_train, y_train) # ('https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html')

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [226]:
l_model.coef_

array([ 1.52313819, -3.09513378, -6.11344785,  3.176714  ,  2.76055364,
       -0.61682343])

In [227]:
l_model.intercept_

38.342900302113875

In [228]:
X_test[:2 , :]

array([[-0.25630176, -1.567052  , -0.6325766 , -1.05974351,  0.47237848,
        -0.22280034],
       [-1.13564877, -0.6483619 ,  1.69069111, -1.40263217, -1.18016149,
         2.18084071]])

The l_model.predict  is a numpy array that contains all the predicted values for the input values in the X_train.

In [229]:
l_model.predict(X_train[:1,:])

array([48.70851724])

In [230]:
l_model.predict(X_test)

array([44.74492951, 19.22511117, 40.59345016, 42.04120187, 37.84579265,
       37.40960226, -0.0821743 , 45.73427096, 47.90196423, 41.88298994,
       15.48140468, 30.78690576, 43.78201449, 44.20807812, 55.1073389 ,
       34.34003231, 45.64939992, 44.97418208, 51.24406616, 45.15971768,
       40.33823291, 41.00168319, 37.96429131, 23.42476838, 25.14116366,
       44.12005674, 35.49680771, 48.04279366, 49.36754022, 44.24703612,
       34.14505764, 43.5036249 , 46.58706697, 25.30090581, 45.48323188,
       38.21463428, 37.0550504 , 15.52444542, 42.6670451 , 32.94791437,
       52.07139893, 34.22699041, 47.81382008, 54.61889444, 44.86187029,
       39.67423384, 12.58992491, 38.53938867, 27.60696551, 40.66042917,
       47.84474288, 48.2638474 , 32.61802735, 48.60776607, 26.25905427,
       47.20480105, 45.71211145, 35.20005662, 36.68626571,  8.64706067,
       12.58992491, 12.86137314, 13.00927819, 38.91191833, 44.38587938,
       11.88541045, 31.38781862, 36.73892437, 36.43898013, 47.38

In [231]:
l_model.score(X_test,y_test)

0.6577005756501637

In [232]:
df.to_csv('Regression X_train.csv')