In [184]:
import pandas as pd
import sklearn.model_selection

Kindly refer to the link mentioned after #

In [185]:
df = pd.read_csv("REV_dataset.csv")
df

No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [186]:
df = df.rename(columns = {"X1 transaction date" : "transation dt",
                      " X2 house age ": "house age ",
                      "X3 distance to the nearest MRT station" : "Nearest mtro",
                    "X4 number of convenience stores" : "nrby stores ",
                    "X5 latitude" : "latitude",
                     "X6 longitude": "longitude",
                    "Y house price of unit area" : "house price"})

In [187]:
df

No  transation dt  X2 house age  Nearest mtro  nrby stores   latitude  \
0      1       2012.917          32.0      84.87882            10  24.98298   
1      2       2012.917          19.5     306.59470             9  24.98034   
2      3       2013.583          13.3     561.98450             5  24.98746   
3      4       2013.500          13.3     561.98450             5  24.98746   
4      5       2012.833           5.0     390.56840             5  24.97937   
..   ...            ...           ...           ...           ...       ...   
409  410       2013.000          13.7    4082.01500             0  24.94155   
410  411       2012.667           5.6      90.45606             9  24.97433   
411  412       2013.250          18.8     390.96960             7  24.97923   
412  413       2013.000           8.1     104.81010             5  24.96674   
413  414       2013.500           6.5      90.45606             9  24.97433   

     longitude  house price  
0    121.54024         37.9  
1    121.53951         42.2  
2    121.54391         47.3  
3    121.54391         54.8  
4    121.54245         43.1  
..         ...          ...  
409  121.50381         15.4  
410  121.54310         50.0  
411  121.53986         40.6  
412  121.54067         52.5  
413  121.54310         63.9  

[414 rows x 8 columns]

In [188]:
# Making X variable
x = df.drop(['house price'] , axis = 1)
x

No  transation dt  X2 house age  Nearest mtro  nrby stores   latitude  \
0      1       2012.917          32.0      84.87882            10  24.98298   
1      2       2012.917          19.5     306.59470             9  24.98034   
2      3       2013.583          13.3     561.98450             5  24.98746   
3      4       2013.500          13.3     561.98450             5  24.98746   
4      5       2012.833           5.0     390.56840             5  24.97937   
..   ...            ...           ...           ...           ...       ...   
409  410       2013.000          13.7    4082.01500             0  24.94155   
410  411       2012.667           5.6      90.45606             9  24.97433   
411  412       2013.250          18.8     390.96960             7  24.97923   
412  413       2013.000           8.1     104.81010             5  24.96674   
413  414       2013.500           6.5      90.45606             9  24.97433   

     longitude  
0    121.54024  
1    121.53951  
2    121.54391  
3    121.54391  
4    121.54245  
..         ...  
409  121.50381  
410  121.54310  
411  121.53986  
412  121.54067  
413  121.54310  

[414 rows x 7 columns]

In [189]:
# Making Y variable
y = df['house price']
y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ... 
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: house price, Length: 414, dtype: float64

In [190]:
print("X_shape : ",x.shape)
print("Y_shape : ",y.shape)

X_shape :  (414, 7)
Y_shape :  (414,)


In [191]:
# ('https://www.greycampus.com/blog/data-science/linear-regression-with-python-scikit-learn')
from sklearn.model_selection import train_test_split 
X_train , X_test , y_train , y_test = train_test_split(x,y , test_size = 0.2 , random_state = 14)

In [192]:
print('X_train_shape : ' , X_train.shape )
print('y_train_shape : ' , y_train.shape )
print('X_test_shape : ' , X_test.shape )
print('y_test_shape : ' , y_test.shape )

X_train_shape :  (331, 7)
y_train_shape :  (331,)
X_test_shape :  (83, 7)
y_test_shape :  (83,)


In [193]:
from sklearn.preprocessing import StandardScaler 
sclr = StandardScaler()
sclr.fit(X_train)
X_train = sclr.transform(X_train)
X_test = sclr.transform(X_test)

In [194]:
from sklearn.linear_model import LinearRegression
l_model = LinearRegression()
l_model.fit(X_train, y_train) # ('https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html')

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [195]:
l_model.coef_

array([-0.6078713 ,  1.52263244, -3.142954  , -6.17921003,  3.20040875,
        2.73551267, -0.68801202])

In [196]:
l_model.intercept_

38.34290030211386

In [197]:
X_test[:2 , :]

array([[ 0.03429735, -0.25630176, -1.567052  , -0.6325766 , -1.05974351,
         0.47237848, -0.22280034],
       [ 0.83154148, -1.13564877, -0.6483619 ,  1.69069111, -1.40263217,
        -1.18016149,  2.18084071]])

The l_model.predict  is a numpy array that contains all the predicted values for the input values in the X_train.

In [198]:
l_model.predict(X_train[:1,:])

array([48.72182198])

In [199]:
l_model.predict(X_test)

array([44.81966881, 18.48110302, 40.83506673, 41.88044721, 38.35547788,
       37.09465525,  0.31896133, 46.67134396, 48.96303312, 41.07370412,
       14.48634683, 30.3831653 , 43.21808627, 43.98987872, 55.05694983,
       35.14641605, 45.13555358, 44.85173357, 50.9312855 , 45.82542688,
       40.7645248 , 40.47154171, 38.57721002, 24.14971086, 24.23269486,
       44.48528826, 36.53858937, 48.57115054, 50.08830888, 45.13265764,
       34.69943874, 43.36073791, 47.46162347, 24.14094387, 46.04316782,
       37.17666961, 36.10258449, 15.64835207, 41.93279106, 32.46481996,
       52.30797004, 33.9727177 , 48.44834361, 54.87743176, 43.84602848,
       39.38518834, 13.06155552, 39.49506714, 28.16872429, 39.7437306 ,
       48.67926439, 48.78211418, 32.27770728, 48.67217842, 25.56391485,
       46.69353856, 46.10160069, 34.46607151, 36.31428732,  9.40527454,
       11.99134899, 13.56883313, 13.1067202 , 38.80945376, 44.18870308,
       11.2263081 , 30.86868027, 37.52191304, 35.89217596, 47.91

In [200]:
l_model.score(X_test,y_test)

0.6533054301722028

In [202]:
df.to_csv('Regression X_train.csv')